### PR TITLE
renaming macos to Darwin

### PR DESCRIPTION
**Pull request by Gregory-Pereira**
Addresses: #181 

#### Summary

While working on #78, I quickly found that the issue is not so much speed but platform enablement for Darwin, a theme I am finding in the repo. This change will help us in bringing alignment between the scripts that are meant to work on both Linux and Darwin, by simpifying / hardneing our process around pieces that are platform dependent

#### Release Note

Change naming conventions from `macOS` to `Darwin`

#### Documentation

No changes in the sigstore dev docs, but the repo `README.md` has been updated

### CODE REVIEW

**Review by smeiklej — APPROVED** [review]
Thanks!

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
Can you also change `.github/workflows` please? These names are load bearing on the CI

**Comment by Gregory-Pereira** [comment]
> Can you also change `.github/workflows` please? These names are load bearing on the CI

This should not be changed, `macos-latest` is the name of the runner, and means something to github actions. If I change this to darwin the runner will not pick it up.

**Comment by Gregory-Pereira** [comment]
My appologies, seems I missunderstood what you were saying, I will update the filenames in the workflows.

**Comment by smeiklej** [comment]
They do, yes.

**Comment by Gregory-Pereira** [comment]
Ready for real Review

**Review by mihaimaruseac — APPROVED** [review]
Thank you!

**Pull request merged**
